services:
    mitmproxy:
        image: mitmproxy/mitmproxy:9.0.1
        ports:
            - "8080:8080"
            - "8081:8081"
        command: [ "mitmweb", "--web-host", "0.0.0.0" ]                
        networks:
            - service_bridge
        depends_on:
            - podinfo


