services:
    mitmproxy:
        image: mitmproxy/mitmproxy:9.0.1
        volumes:
            - ./scripts:/scripts
        ports:
            - "8080:8080"
            - "8081:8081"
        command: [ "mitmweb", "--verbose", "-s", "/scripts/flow-counter.py", "--web-host", "0.0.0.0", "--mode", "reverse:http://podinfo:9898" ]                
        networks:
            - service_bridge
        depends_on:
            - podinfo


